version: '3'

services:
  chat_server:
    build:
      context: .
      dockerfile: ./cmd/chat_server/Dockerfile
    ports:
      - 8989:8989
  node1:
    build:
      context: .
      dockerfile: ./cmd/node/Dockerfile
    ports:
      - 8980:8989
  node2:
    build:
      context: .
      dockerfile: ./cmd/node/Dockerfile
    ports:
      - 8981:8989
  node3:
    build:
      context: .
      dockerfile: ./cmd/node/Dockerfile
    ports:
      - 8982:8989
