version: '3'

services:
  chat_server:
    build: ./chat_server
    volumes:
      - ./chat_server:/app
    ports:
      - 8989:8989
  node1:
    build: ./node
    volumes:
      - ./node:/app
    ports:
      - 8980:8989
  node2:
    build: ./node
    volumes:
      - ./node:/app
    ports:
      - 8981:8989
  node3:
    build: ./node
    volumes:
      - ./node:/app
    ports:
      - 8982:8989
