ROUTER_IP_IDX = 1
ROUTER_PORT = 7777
DESTINATION__IP_IDX = 2
CODE_ROUTE     = "11"

ST_NODE_IP_IDX = 0
ND_NODE_IP_IDX = 1
RD_NODE_IP_IDX = 2
DST_IP_IDX = 3

CLOSE_SOCKET_FLAG = '1'
KEEP_SOCKET_FLAG = '0'

MESSAGE_SIZE_LEN = 5

KEY_SIZE = 4096